<h5>Custom Reports</h5>
<h5>Catalog</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/custom/cat_titles_by_various.pl">Titles By Various Criteria</a></li>
		<li><a href="/cgi-bin/koha/reports/custom/cat_lost.pl">Copies by Status</a></li>
		<li><a href="/cgi-bin/koha/reports/custom/circ_reserves.pl">Titles on Hold</a></li>
		<li><a href="/cgi-bin/koha/reports/custom/cat_items_noitype.pl">Items With No Item Type</a></li>
		<li><a href="/cgi-bin/koha/reports/custom/cat_nocallnumber.pl">Copies Without a Call Number</a></li>
		<li><a href="/cgi-bin/koha/reports/custom/cat_newcopies.pl">New Copies</a></li>
		<li><a href="/cgi-bin/koha/reports/custom/cat_age.pl">Collection Age</a></li>
		<li><a href="/cgi-bin/koha/reports/custom/cat_inventory.pl">Catalog Inventory</a></li>
		<li><a href="/cgi-bin/koha/reports/custom/cat_usedbarcodes.pl">Used Barcodes</a></li>
	</ul>
<h5>Circulation</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/custom/circ_issued.pl">Checked Out Books</a></li>
		<li><a href="/cgi-bin/koha/reports/custom/account_overdues_fines.pl">Overdue Copies And Fines</a></li>
		<li><a href="/cgi-bin/koha/reports/custom/circ_stats_noissues.pl">Copies With No Checkouts</a></li>
		<li><a href="/cgi-bin/koha/reports/custom/circ_all_issues.pl">All Checkouts</a></li>
		<li><a href="/cgi-bin/koha/reports/custom/circ_yearly_total.pl">Yearly Circulation Totals</a></li>
		<li><a href="/cgi-bin/koha/reports/custom/circ_monthly_total.pl">Monthly Circulation Totals</a></li>
	</ul>
<h5>Patrons</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/custom/account_fines.pl">Fines</a></li>
		<li><a href="/cgi-bin/koha/reports/custom/account_payments.pl">Payments</a></li>
		<li><a href="/cgi-bin/koha/reports/custom/borrowers_messages.pl">Borrower Messages</a></li>
		<li><a href="/cgi-bin/koha/reports/custom/borrowers_by_status.pl">List Borrowers by Status</a></li>
	</ul>
<h5>Guided Reports</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/guided_reports.pl">Guided Reports</a></li>
	</ul>

<h5>Statistics wizards</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/acquisitions_stats.pl">Acquisitions</a></li>
		<li><a href="/cgi-bin/koha/reports/borrowers_stats.pl">Patrons</a></li>
		<li><a href="/cgi-bin/koha/reports/catalogue_stats.pl">Catalog</a></li>
		<li><a href="/cgi-bin/koha/reports/issues_stats.pl">Circulation</a></li>
                <li><a href="/cgi-bin/koha/reports/serials_stats.pl">Serials</a></li>
	</ul>


	<h5>Top Lists</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/bor_issues_top.pl">Patrons with the most checkouts</a></li>
		<li><a href="/cgi-bin/koha/reports/cat_issues_top.pl">Most-Circulated Items</a></li>
	</ul>
	
	<h5>Inactive</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/borrowers_out.pl">Patrons who haven't checked out</a></li>
		<li><a href="/cgi-bin/koha/reports/catalogue_out.pl">Items with no checkouts</a></li>
	</ul>


	<h5>Other</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/itemslost.pl">Lost Items</a></li>
		<li><a href="/cgi-bin/koha/reports/manager.pl?report_name=itemtypes">Catalog by Item Type</a></li>
		<li><a href="/cgi-bin/koha/reports/issues_avg_stats.pl">Average loan time</a></li>
	</ul>
